data = [
  {
    "SrNo": "1374",
    "ReturnId": "62572",
    "AcknowledgementNo": "ACK-131983290283772084",
    "EntryDate": "29/03/19",
    "Zone": "JALANDHAR",
    "Sector": "10",
    "Colony": "Makhdoom Pura",
    "HouseNo": "ES-107",
    "Owner": "TIRATH SINGH / MR HAZARA SINGH / 9914338184",
    "Floor": "Ground Floor / 729.00 / Non-Residential / Self Occupied / Pucca / 2187.00",
    "ResidentialRate": "0",
    "CommercialRate": "0",
    "ExemptionCategory": "Person, who had served, or are serving, in any rank, whether as a combatant or a non-combatant, in the Naval, Military or Air Forces of the Union of India",
    "LandUsedType": "The building and land of Hospitals or Dispensaries owned by the State Government",
    "Usage": "Built Up",
    "PlotArea": "81",
    "TotalCoveredArea": "729",
    "GrossTax": "2187",
    "FireCharges": "0",
    "InterestAmt": "0",
    "Penalty": "0",
    "Rebate": "0",
    "ExemptionAmt": "2187",
    "TaxAmt": "0",
    "AmountPaid": "",
    "PaymentMode": "",
    "TransactionID": "",
    "Bank": "",
    "G8BookNo": "",
    "G8ReceiptNo": "",
    "PaymentDate": "29/03/19",
    "PropertyType": "Non-Residential",
    "BuildingCategory": "Commercial buildings including Restaurants (except multiplexes, malls, marriage palaces)",
    "Session": "2018-2019",
    "Remarks": "",
    "uuid": "c7fa93ac-8f20-4443-82df-393292f5fefc",
    "previous_returnid": None,
    "status": "STAGE1",
    "tenantid": None,
    "batchname": None,
    "new_propertyid": None,
    "new_locality_code": "JALLC635"
  },
  {
    "SrNo": "3517",
    "ReturnId": "62571",
    "AcknowledgementNo": "ACK-131983288534291780",
    "EntryDate": "29/03/19",
    "Zone": "JALANDHAR",
    "Sector": "7",
    "Colony": "Defence Colony",
    "HouseNo": "64",
    "Owner": "MAJ.GEN.TIRATH SINGH / MR HAZARA SINGH / 9914338184",
    "Floor": "Ground Floor / 2403.00 / Residential / Self Occupied / Pucca / 1335.00Ground Floor - Vacant / 2097.00 / Residential / Self Occupied / Pucca / 583.00",
    "ResidentialRate": "0",
    "CommercialRate": "0",
    "ExemptionCategory": "Person, who had served, or are serving, in any rank, whether as a combatant or a non-combatant, in the Naval, Military or Air Forces of the Union of India",
    "LandUsedType": "The building and land of Hospitals or Dispensaries owned by the State Government",
    "Usage": "Built Up",
    "PlotArea": "500",
    "TotalCoveredArea": "2403",
    "GrossTax": "1918",
    "FireCharges": "0",
    "InterestAmt": "0",
    "Penalty": "0",
    "Rebate": "0",
    "ExemptionAmt": "1918",
    "TaxAmt": "0",
    "AmountPaid": "",
    "PaymentMode": "",
    "TransactionID": "",
    "Bank": "",
    "G8BookNo": "",
    "G8ReceiptNo": "",
    "PaymentDate": "29/03/19",
    "PropertyType": "Residential",
    "BuildingCategory": "Residential Houses",
    "Session": "2018-2019",
    "Remarks": "",
    "uuid": "69689bc2-11fa-4188-953c-8beab97e0a55",
    "previous_returnid": None,
    "status": "STAGE1",
    "tenantid": None,
    "batchname": None,
    "new_propertyid": None,
    "new_locality_code": "JALLC134"
  }
]